; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [platformio]
; default_envs = RPiPicoW_Lib_CustomHandler

[env:RPiPicoW_Lib]
platform = raspberrypi
board = rpipicow
framework = arduino
;board_build.core = earlephilhower
lib_deps = 
    arduino-libraries/Ethernet@^2.0.2

; [env:RPiPicoW_Lib_Authentication]
; platform = raspberrypi
; board = rpipicow
; framework = arduino
; ;board_build.core = earlephilhower
; build_src_filter = 
;     -<./main.cpp>
; 	+<../examples/authentication.cpp>
; 	+<../src/Configuration.cpp>
; lib_deps = 
; 	;roman-gobrei/HttpServer
; 	arduino-libraries/Ethernet@^2.0.2

; [env:RPiPicoW_Lib_HttpServer]
; platform = raspberrypi
; board = rpipicow
; framework = arduino
; ;board_build.core = earlephilhower
; build_src_filter = 
; 	-<./main.cpp>
; 	+<../examples/httpServer.cpp>
; 	+<../src/Configuration.cpp>
; 	+<../src/HttpParser.cpp>
; lib_deps = 
; 	;roman-gobrei/HttpServer
; 	arduino-libraries/Ethernet@^2.0.2

; [env:RPiPicoW_Lib_CustomHandler]
; platform = raspberrypi
; board = rpipicow
; framework = arduino
; ;board_build.core = earlephilhower
; build_src_filter = 
;     +<include/>
; 	+<src/>
; 	-<./main.cpp>
; 	+<../examples/customHandler.cpp>
; 	+<../src/Configuration.cpp>
; lib_deps = 
; 	;roman-gobrei/HttpServer
; 	arduino-libraries/Ethernet@^2.0.2