; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = rpipicow

[env:rpipicow]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
framework = arduino
lib_deps = 
	bakercp/Logger@^1.0.3
	bblanchon/ArduinoJson@^7.4.3
	adafruit/DHT sensor library@^1.4.7
	khoih-prog/RPI_PICO_TimerInterrupt@^1.3.1
	adafruit/Adafruit AHTX0@^2.0.6
	bblanchon/ArduinoJson@^7.4.3

[env:wiznet_5500_evb_pico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = wiznet_5500_evb_pico2
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
framework = arduino
build_flags = 
	'-D SHIELD="W5500-EVB-Pico2"'
lib_deps = 
	roman-gobrei/HttpServer@^1.1.0
	arduino-libraries/Ethernet@^2.0.2
	bakercp/Logger@^1.0.3
	bblanchon/ArduinoJson@^7.4.3
	adafruit/DHT sensor library@^1.4.7
	khoih-prog/RPI_PICO_TimerInterrupt@^1.3.1
	adafruit/Adafruit AHTX0@^2.0.6
	arduino-libraries/ArduinoMDNS@^1.0.1
	bblanchon/ArduinoJson@^7.4.3

[env:rpipicow_check]
platform = raspberrypi
board = rpipicow
board_build.filesystem_size = 0.5m
check_skip_packages = yes
check_tool = cppcheck
check_flags = cppcheck: --suppress=*:*/.pio/*
framework = arduino
lib_deps = 
	bakercp/Logger@^1.0.3
	bblanchon/ArduinoJson@^7.4.3
	adafruit/DHT sensor library@^1.4.7
	khoih-prog/RPI_PICO_TimerInterrupt@^1.3.1
	adafruit/Adafruit AHTX0@^2.0.6

[env:test]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = wiznet_5500_evb_pico2
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
build_src_filter = +<*> -<main.cpp>
framework = arduino
test_framework = unity
test_build_src = yes
build_flags = 
	'-D SHIELD="W5500-EVB-Pico2"'
lib_deps = 
	roman-gobrei/HttpServer@^1.1.0
	arduino-libraries/Ethernet@^2.0.2
	bakercp/Logger@^1.0.3
	bblanchon/ArduinoJson@^7.4.3
	adafruit/DHT sensor library@^1.4.7
	khoih-prog/RPI_PICO_TimerInterrupt@^1.3.1
	adafruit/Adafruit AHTX0@^2.0.6
	arduino-libraries/ArduinoMDNS@^1.0.1
